2021-09-27 13:40:48,826 INFO    MainThread:17284 [wandb_setup.py:_flush():69] setting env: {}
2021-09-27 13:40:48,826 INFO    MainThread:17284 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-27 13:40:48,826 INFO    MainThread:17284 [wandb_init.py:_log_setup():348] Logging user logs to C:\Users\astelzl\Documents\02_DEV\01_Code_Thesis\NER-prodigy-logWandB\wandb\run-20210927_134048-1zko1o61\logs\debug.log
2021-09-27 13:40:48,827 INFO    MainThread:17284 [wandb_init.py:_log_setup():349] Logging internal logs to C:\Users\astelzl\Documents\02_DEV\01_Code_Thesis\NER-prodigy-logWandB\wandb\run-20210927_134048-1zko1o61\logs\debug-internal.log
2021-09-27 13:40:48,827 INFO    MainThread:17284 [wandb_init.py:init():381] calling init triggers
2021-09-27 13:40:48,828 INFO    MainThread:17284 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-27 13:40:48,828 INFO    MainThread:17284 [wandb_init.py:init():401] re-initializing run, found existing run on stack: nfgzsfgz
2021-09-27 13:40:48,829 INFO    MainThread:17284 [wandb_run.py:finish():1275] finishing run alfred-ls/Prodigy_NER/nfgzsfgz
2021-09-27 13:40:48,830 INFO    MainThread:17284 [jupyter.py:save_history():353] not saving jupyter history
2021-09-27 13:40:48,830 INFO    MainThread:17284 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-27 13:40:48,830 INFO    MainThread:17284 [wandb_init.py:_jupyter_teardown():281] cleaning up jupyter logic
2021-09-27 13:40:48,830 INFO    MainThread:17284 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-27 13:40:48,830 INFO    MainThread:17284 [wandb_run.py:_restore():1547] restore
2021-09-27 13:40:49,048 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 862
}

2021-09-27 13:40:49,340 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 862
}

2021-09-27 13:40:49,694 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 4730
}

2021-09-27 13:40:49,796 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 4756
}

2021-09-27 13:40:49,901 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 4756
}

2021-09-27 13:40:50,004 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}

2021-09-27 13:40:50,105 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}

2021-09-27 13:40:50,206 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}

2021-09-27 13:40:50,307 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}

2021-09-27 13:40:50,409 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}

2021-09-27 13:40:50,510 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}

2021-09-27 13:40:50,831 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}

2021-09-27 13:40:51,282 INFO    MainThread:17284 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4756
  total_bytes: 4756
}
local_info {
}

2021-09-27 13:40:52,350 INFO    MainThread:17284 [wandb_run.py:_show_files():1947] logging synced files
2021-09-27 13:40:52,354 INFO    MainThread:17284 [wandb_init.py:init():430] starting backend
2021-09-27 13:40:52,354 INFO    MainThread:17284 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-27 13:40:52,358 INFO    MainThread:17284 [backend.py:ensure_launched():135] starting backend process...
2021-09-27 13:40:52,416 INFO    MainThread:17284 [backend.py:ensure_launched():139] started backend process with pid: 16992
2021-09-27 13:40:52,417 INFO    MainThread:17284 [wandb_init.py:init():435] backend started and connected
2021-09-27 13:40:52,429 INFO    MainThread:17284 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-27 13:40:52,429 INFO    MainThread:17284 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-27 13:40:52,429 INFO    MainThread:17284 [wandb_init.py:init():494] updated telemetry
2021-09-27 13:40:52,430 INFO    MainThread:17284 [wandb_init.py:init():517] communicating current version
2021-09-27 13:40:53,206 INFO    MainThread:17284 [wandb_init.py:init():522] got version response 
2021-09-27 13:40:53,206 INFO    MainThread:17284 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-27 13:40:53,494 INFO    MainThread:17284 [wandb_init.py:init():557] starting run threads in backend
2021-09-27 13:40:54,318 INFO    MainThread:17284 [wandb_run.py:_console_start():1605] atexit reg
2021-09-27 13:40:54,319 INFO    MainThread:17284 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-27 13:40:54,319 INFO    MainThread:17284 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-27 13:40:54,321 INFO    MainThread:17284 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-27 13:40:54,321 INFO    MainThread:17284 [wandb_init.py:init():582] run started, returning control to user process
2021-09-27 14:38:29,363 INFO    MainThread:17284 [wandb_setup.py:_flush():69] setting env: {}
2021-09-27 14:38:29,364 INFO    MainThread:17284 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-27 14:38:29,365 INFO    MainThread:17284 [wandb_init.py:_log_setup():348] Logging user logs to C:\Users\astelzl\Documents\02_DEV\01_Code_Thesis\NER-prodigy-logWandB\wandb\run-20210927_143829-37kr1pzz\logs\debug.log
2021-09-27 14:38:29,365 INFO    MainThread:17284 [wandb_init.py:_log_setup():349] Logging internal logs to C:\Users\astelzl\Documents\02_DEV\01_Code_Thesis\NER-prodigy-logWandB\wandb\run-20210927_143829-37kr1pzz\logs\debug-internal.log
2021-09-27 14:38:29,367 INFO    MainThread:17284 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B4BC408DF0>
2021-09-27 14:38:29,372 INFO    MainThread:17284 [wandb_init.py:init():381] calling init triggers
2021-09-27 14:38:29,373 INFO    MainThread:17284 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-27 14:38:29,373 INFO    MainThread:17284 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 1zko1o61
2021-09-27 14:38:29,375 INFO    MainThread:17284 [wandb_run.py:finish():1275] finishing run alfred-ls/Prodigy_NER/1zko1o61
